id: P8436F858
initial_creation_type: input
source_metadata:
  title: Damngak Dzö Series
  language: es
  description: 'Texts belonging to (and related to) the Damgnak Dzö (gdams ngag mdzod)
    or Treasury of Instructions, one of the five treasuries of Jamgön Kongtrul Lodrö
    Thayé (1813–1899):'
  volume:
    dd89385eac964571b72f6b699c5688e9:
      title: The Bodhisattva’s Garland of Jewels
      parent: Kadam
    7968b01838254140b2aa24fa191be343:
      title: The Lamp for the Path to Enlightenment
      parent: Kadam
    407782eef5764c2d8e64de1ccdc7bb66:
      title: Seven Points of Training the Mind According to the Great Vehicle
      parent: Kadam
    2b5fb692b41b49c58cb499cad301f08a:
      title: Three Principal Aspects of the Path
      parent: Kadam
    0a8fca3618984a3a91949007a164c8f7:
      title: Supplement to the Omniscient Ngorchen Kunga Zangpo’s Prayer to the Lineage
        of Parting from the Four Attachments
      parent: Sakya Lamdré
    9d1fc0fd8c444121a07bbd47e207562c:
      title: Parting from the Four Attachments
      parent: Sakya Lamdré
    0fda663db6fe4898b22b06b22c88f171:
      title: Prayer to the Lineage of Parting from the Four Attachments
      parent: Sakya Lamdré
    8f961ea7c5d64c0daae8e04ca0e7efe6:
      title: Nubpa Rigdzin Drak's Parting from the Four Attachments
      parent: Sakya Lamdré
    af1525d3a2594577bbfe619003dfea8e:
      title: The Instructions on Parting from the Four Attachments
      parent: Sakya Lamdré
    b5599b041d2c4ac9ae24777b6e29c154:
      title: Sakya Paṇḍita’s Instruction on Parting from the Four Attachments
      parent: Sakya Lamdré
    41ed6d099af24a8a8cf03d354b433a49:
      title: 'A Casket of Sacred Dharma: Stages of Meditation on Dependent Arising'
      parent: Marpa Kagyü
    12e0ce0dd442430280f42f9b326f693b:
      title: The Ganges Mahāmudrā Instructions
      parent: Marpa Kagyü
    87892b06903343d2b2988bc858fde5d9:
      title: 'The Sweet-Sounding Song that Fulfils All Aims: A Prayer to Noble Tārā
        Combined with Her Root Mantra'
      parent: Miscellaneous
    aea551a6f72d4dd7b75a0778fbd1fd40:
      title: Vajra Speech of the Prayer to Noble Avalokiteśvara from the Great Siddha
        Thangtong Gyalpo's Lifetime as Bhikṣu Padma Karpo
      parent: Miscellaneous
created_at: '2022-03-01T03:21:42.539780'
last_modified_at: '2022-03-01T03:21:42.539782'
